[book]
authors = ["ylll"]
language = "zh"
multilingual = false
src = "src"
title = "sie"
[output.html]
theme = "src/theme"
additional-css = ["add/expandable-chapters.css"]
additional-js = ["add/expandable-chapters.js", "add/gitbook.js"]