[book]
authors = ["ylll"]
language = "zh"
multilingual = false
src = "src"
title = "sie"

[output.html]
no-section-label = true
copy-fonts = false
theme = "src/theme"

[output.html.fold]
enable = true
level = 0